name: Build project

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Salvager/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Salvager
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: Salvager/Build/${{ matrix.targetPlatform }}

      - name: Create ZIP Archive
        run: |
          mkdir -p Salvager/Build
          zip -r Salvager/Build/StandaloneWindows64.zip Salvager/Build/${{ matrix.targetPlatform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: Salvager/Build/StandaloneWindows64.zip

  release:
    name: Create GitHub Release
    needs: buildForAllSupportedPlatforms
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows64
          path: artifacts

      - name: List files for debugging
        run: ls -lh artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Automated build release."
          draft: false
          prerelease: false
          files: artifacts/StandaloneWindows64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
